services:
  web_grupo1:
    build: .
    container_name: web_grupo1
    env_file: .env
    restart: always
    networks: -web
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  web:
    external: true
